name: Continuous Deployment

on:
  push:
    branches: [ main ]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Criar release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v1.0.${{ github.run_number }}
          name: Release automática
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}