name: CD

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    env:
      HUSKY: 0

    steps:
      - uses: actions/checkout@v6

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '4.0.3'
          bundler-cache: true

      - name: Rodar testes (RSpec)
        run: bundle exec rspec

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 20

      - name: Install deps
        run: npm install

      - name: Run semantic-release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}